In [2]:
import numpy as np

# Creating Arrays

In [7]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
             dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[[ 1.5  2.   3. ]
  [ 4.   5.   6. ]]

 [[ 3.   2.   1. ]
  [ 4.   5.   6. ]]]


Initial Placeholders

In [9]:
np.zeros((3,4)) # Create an array of zeros


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.ones((2,3,4),dtype=np.int16) # Create an array of ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
d = np.arange(10,25,5) # Create an array of evenly
                          # spaced values (step value)
d

array([10, 15, 20])

In [13]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)


array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [14]:
e = np.full((2,2),7) # Create a constant array
e

array([[7, 7],
       [7, 7]])

In [15]:
f = np.eye(2) # Create a 2X2 identity matrix
f

array([[ 1.,  0.],
       [ 0.,  1.]])

In [16]:
np.random.random((2,2)) # Create an array with random values


array([[ 0.78275204,  0.02771207],
       [ 0.44847024,  0.25007092]])

In [17]:
np.empty((3,2)) # Create an empty array

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

# Inspecting Arrays

In [24]:
print('a=' + str(a)) 
print(a.shape) #Array dimensions
print(len(a)) #Length of array
print(b.ndim) #Number of array dimensions
print(e.size) #Number of array elements
print(b.dtype) #Data type of array elements
print(b.dtype.name) #Name of data type
b.astype(int)   #Convert an array to a different type

a=[1 2 3]
(3,)
3
2
4
float64
float64


array([[1, 2, 3],
       [4, 5, 6]])

# Asking For Help

In [25]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Array Mathematics

## Aritmetic Operations

In [27]:
g = a - b #Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [29]:
b + a #Addition

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [30]:
np.add(b,a) #Addition

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [31]:
a / b #Division

array([[ 0.66666667,  1.        ,  1.        ],
       [ 0.25      ,  0.4       ,  0.5       ]])

In [32]:
np.divide(a,b) #Division

array([[ 0.66666667,  1.        ,  1.        ],
       [ 0.25      ,  0.4       ,  0.5       ]])

In [33]:
a * b #Multiplication

array([[  1.5,   4. ,   9. ],
       [  4. ,  10. ,  18. ]])

In [40]:
np.multiply(a,b) #Multiplication


array([[  1.5,   4. ,   9. ],
       [  4. ,  10. ,  18. ]])

In [39]:
np.exp(b) #Exponentiation


array([[   4.48168907,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349]])

In [38]:
np.sqrt(b) #Square root


array([[ 1.22474487,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [37]:
np.sin(a) #Print sines of an array


array([ 0.84147098,  0.90929743,  0.14112001])

In [36]:
np.cos(b) #Element-wise cosine


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [35]:
np.log(a) #Element-wise natural logarithm


array([ 0.        ,  0.69314718,  1.09861229])

In [34]:
e.dot(f) #Dot product

array([[ 7.,  7.],
       [ 7.,  7.]])

## Comparisons

In [41]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]], dtype=bool)

In [42]:
a < 2 #Element-wise comparison

array([ True, False, False], dtype=bool)

In [43]:
np.array_equal(a, b) #Array-wise comparison

False

## Aggregate Functions

In [46]:
a.sum() #Array-wise sum
a.min() #Array-wise minimum value
b.max(axis=0) #Maximum value of an array row
b.cumsum(axis=1) #Cumulative sum of the elements
a.mean() #Mean
np.std(b) #Standard deviation

1.5920810978785667

# Copying Arrays

In [47]:
h = a.view() #Create a view of the array with the same data
h

array([1, 2, 3])

In [50]:
h[1]=4
print(a)
h

[1 4 3]


array([1, 4, 3])

In [51]:
h = a.copy() #Create a deep copy of the array
h

array([1, 4, 3])

In [52]:
h[0]=5
print(a)
h

[1 4 3]


array([5, 4, 3])

# Sorting Arrays

In [58]:
a.sort() #Sort an array
c.sort(axis=0) #Sort the elements of an array's axis
print(a)
print(c)

[1 3 4]
[[[ 1.5  2.   1. ]
  [ 4.   5.   6. ]]

 [[ 3.   2.   3. ]
  [ 4.   5.   6. ]]]


# Subsetting, Slicing, Indexing

In [59]:
a[2] #Select the element at the 2nd index

4

In [60]:
b[1,2] #Select the element at row 0 column 2
       #(equivalent to b[1][2])

6.0

In [61]:
a[0:2] #Select items at index 0 and 1

array([1, 3])

In [62]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([ 2.,  5.])

In [63]:
b[:1] #Select all items at row 0
      #(equivalent to b[0:1, :])

array([[ 1.5,  2. ,  3. ]])

In [64]:
c[1,...] #Same as [1,:,:]

array([[ 3.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [65]:
a[ : :-1] #Reversed array a

array([4, 3, 1])

In [66]:
a[a<2] #Select elements from a less than 2

array([1])

In [67]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([ 4. ,  2. ,  6. ,  1.5])

In [68]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns


array([[ 4. ,  5. ,  6. ,  4. ],
       [ 1.5,  2. ,  3. ,  1.5],
       [ 4. ,  5. ,  6. ,  4. ],
       [ 1.5,  2. ,  3. ,  1.5]])

# Array Manipulation

In [69]:
#Transposing Array
i = np.transpose(b) #Permute array dimensions


In [70]:
i.T                 # Permute array dimensions


array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [71]:
#Changing Array Shape
b.ravel()       #Flatten the array


array([ 1.5,  2. ,  3. ,  4. ,  5. ,  6. ])

In [72]:
g.reshape(3,-2) #Reshape, but don’t change data



array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [76]:
#Adding/Removing Elements
np.append(h,g) #Append items to an array
np.insert(a, 1, 5) #Insert items in an array
np.delete(a,[1]) #Delete items from an array



array([1, 4])

In [ ]:
#Combining Arrays
np.concatenate((a,d),axis=0) #Concatenate arrays
np.vstack((a,b)) #Stack arrays vertically (row-wise)
np.r_[e,f] Stack arrays vertically (row-wise)
np.hstack((e,f)) Stack arrays horizontally (column-wise)
np.column_stack((a,d)) Create stacked column-wise arrays
np.c_[a,d] Create stacked column-wise arrays


In [74]:
#Splitting Arrays
np.hsplit(a,3) #Split the array horizontally at the 3rd index
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[ 1.5,  2. ,  1. ],
         [ 4. ,  5. ,  6. ]]]), array([[[ 3.,  2.,  3.],
         [ 4.,  5.,  6.]]])]