#### 0 Crea un vector con los primeros 20 número naturales y crea un vector de 4 filas y 5 columnas: utilizar función reshape

In [1]:
import numpy as np

In [155]:
v = np.arange(1,21)
v2 =v.reshape(4,5)
print(v2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### 1 Suma el primer número de la segunda línea a todos los números de la última columna

In [156]:
v2[:,-1] =  v2[:,-1] + v2[1,0]
print(v2)

[[ 1  2  3  4 11]
 [ 6  7  8  9 16]
 [11 12 13 14 21]
 [16 17 18 19 26]]


#### 2 Crea un vector con valores que vayan desde 10 a 49 e invierte el vector sin utilizar la función flip

In [2]:
import numpy as np

In [3]:
a = np.arange(10,50)
a = a[::-1]
print(a)

# explicación https://stackoverflow.com/questions/15748001/reversed-array-in-numpy

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 3 Crea un array 5x5 y rellenalo con el patrón de una trabla de ajedrez: 0 = negro, 1 = blanco
<img src ="https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Checkerboard_pattern.svg/500px-Checkerboard_pattern.svg.png">


In [159]:
a = np.zeros((5,5),dtype = int)
a[::2,1::2] = 1  #lineas pares / columnas impares
a[1::2,0::2] = 1 #lineas impares / columnas pares

print(a)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


#### 4 Crea una matriz 5x5 con valores entre 0 y 5. Utilizar función arange

In [4]:
a = np.zeros((5,5), dtype = int)
a = a + np.arange(5)

#### 5 Genera un vector random de tamaño 10 y ordénalo

In [161]:
a = np.random.random(10)
a.sort()
print(a)

[0.17862053 0.28996648 0.43903193 0.4966028  0.62369431 0.80633814
 0.84617559 0.88090965 0.91100732 0.92093001]


#### 6 Genera un vector 2D aleatorio (5 x10) de números enteros y sustrae a cada elemento la media de cada línea de la matriz
*Puedes utilizar los métodos mean y reshape para facilitar la solución

In [162]:
a = np.random.randint(5,size=(5,10))
print(a)

y = a - a.mean(axis = 1).reshape(-1,1) #opcion A
print(y)

z = a - a.mean(axis = 1, keepdims = True) #opcion B
print(z)


    

[[4 2 1 1 4 0 0 4 4 1]
 [1 3 4 0 3 4 1 1 4 0]
 [3 4 1 1 3 2 1 0 2 3]
 [4 4 2 0 3 3 1 3 4 3]
 [1 1 0 0 2 1 3 4 2 1]]
[[ 1.9 -0.1 -1.1 -1.1  1.9 -2.1 -2.1  1.9  1.9 -1.1]
 [-1.1  0.9  1.9 -2.1  0.9  1.9 -1.1 -1.1  1.9 -2.1]
 [ 1.   2.  -1.  -1.   1.   0.  -1.  -2.   0.   1. ]
 [ 1.3  1.3 -0.7 -2.7  0.3  0.3 -1.7  0.3  1.3  0.3]
 [-0.5 -0.5 -1.5 -1.5  0.5 -0.5  1.5  2.5  0.5 -0.5]]
[[ 1.9 -0.1 -1.1 -1.1  1.9 -2.1 -2.1  1.9  1.9 -1.1]
 [-1.1  0.9  1.9 -2.1  0.9  1.9 -1.1 -1.1  1.9 -2.1]
 [ 1.   2.  -1.  -1.   1.   0.  -1.  -2.   0.   1. ]
 [ 1.3  1.3 -0.7 -2.7  0.3  0.3 -1.7  0.3  1.3  0.3]
 [-0.5 -0.5 -1.5 -1.5  0.5 -0.5  1.5  2.5  0.5 -0.5]]


#### 7 Escribe una función que ordene un array indicando un número de columna: utilizar la función argsort,
Ejemplo:

M1 =[[2 4 2]
 [4 1 3]
 [3 0 0]] <br>
Si la ordenamos por la columna = 1 => <br>
[[3 0 0]
 [4 1 3]
 [2 4 2]]

In [6]:
Z = np.random.randint(0,5,(3,3))
print(Z)
a = Z[:,1].argsort()
print(a)
#print(a)
print(Z[a])


[[2 4 2]
 [4 1 3]
 [3 0 0]]
[2 1 0]
[[3 0 0]
 [4 1 3]
 [2 4 2]]


#### 8 Desarrolla una función que aplique la exponencial a cada elemento de una matriz/vector.


In [4]:
import numpy as np
import math


v = np.random.random(size=(5,1))
n = v.shape[0]


u = np.zeros((n,1))


for i in range(n):
    u[i]= math.exp(v[i])
print(u)
    
u2 = np.exp(v)
print(u2)


[[1.43777922]
 [1.5739332 ]
 [2.42125315]
 [1.02770899]
 [1.61513626]]
[[1.43777922]
 [1.5739332 ]
 [2.42125315]
 [1.02770899]
 [1.61513626]]
